version: '3.8'

services:
  # PHP + Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astral_app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=astral_db
      - DB_PORT=3306
      - DB_DATABASE=astral_db
      - DB_USERNAME=astral_user
      - DB_PASSWORD=astral_password
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: >
      sh -c "if [ ! -f .env ]; then cp .env.example .env; fi &&
             php artisan key:generate &&
             php artisan migrate &&
             php-fpm"

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: astral_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: astral_password
      MYSQL_DATABASE: astral_db
      MYSQL_USER: astral_user
      MYSQL_PASSWORD: astral_password
    volumes:
      - db_data:/var/lib/mysql

  # Laravel Queue Worker (optional)
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astral_queue
    command: php artisan queue:work
    depends_on:
      - db
    networks:
      - astral_network

  # Nginx for routing frontend and backend (optional)
  nginx:
    image: nginx:alpine
    container_name: astral_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - astral_network

networks:
  astral_network:
    driver: bridge

volumes:
  db_data:
    driver: local
